const fs = require("fs");
const path = require("path");

// List your React app routes here
const routes = [
  "/",
  "/about",
  "/features/cloud-based-school-managment-system",
  "/features/cutting-edge-technologies",
  "/features/computer-based-exam-solutions",
  "/features/ai-driven-school-management",
  "/features/data-security",
  "/features/students-and-parent-portals",
  "/features/online-daily-diary",
  "/features/school-management-mobile-app",
  "/features/whatsapp-messaging",
  "/features/biometric-attendance",
  "/features/salary-and-fee-management",
  "/features/inventory-management",
  "/features/student-and-staff-ledgers",
  "/features/remainders-for-fee-collection",
  "/features/exams-and-results-management",
  "/features/reporting",
  "/features/multi-campuses-management",
  "/features/school-front-website",
  "/user-manual",
  "/user-manual/dashboard",
  "/user-manual/visitors-meeting",
  "/user-manual/phone-call-log",
  "/user-manual/postal-dispatch",
  "/user-manual/postal-recieve",
  "/user-manual/online-complains-list",
  "/user-manual/configure-front-office",
  "/user-manual/teaching-staff",
  "/user-manual/non-teaching-staff",
  "/user-manual/staff-todos",
  "/user-manual/staff-withdraw",
  "/user-manual/staff-review",
  "/user-manual/feedback-list",
  "/user-manual/new-admission",
  "/user-manual/students-list",
  "/user-manual/online-admissions",
  "/user-manual/family-record",
  "/user-manual/promote-students",
  "/user-manual/withdraw-students",
  "/user-manual/passout-students",
  "/user-manual/students-review",
  "/user-manual/feedback-record",
  "/user-manual/student-attendance",
  "/user-manual/staff-attendance",
  "/user-manual/leave-request",
  "/user-manual/inventory",
  "/user-manual/purchase-inventory",
  "/user-manual/purchase-list",
  "/user-manual/issue-inventory",
  "/user-manual/invoice-list",
  "/user-manual/supplier",
  "/user-manual/recieve-fee",
  "/user-manual/refund-payment",
  "/user-manual/update-fee",
  "/user-manual/update-fee-list",
  "/user-manual/scholarship",
  "/user-manual/fine-management",
  "/user-manual/discounts",
  "/user-manual/student-account-adjust",
  "/user-manual/fee-comitment-list",
  "/user-manual/default-students",
  "/user-manual/calender",
  "/user-manual/salary-cycle",
  "/user-manual/generate-vouchers",
  "/user-manual/print-vouchers",
  "/user-manual/withdraw-amount",
  "/user-manual/students-account",
  "/user-manual/staff-account",
  "/user-manual/supplier-account",
  "/user-manual/family-wise-account",
  "/user-manual/salary-deduction",
  "/user-manual/configure-exam",
  "/user-manual/configure-papers",
  "/user-manual/date-sheet",
  "/user-manual/add-result",
  "/user-manual/subject-wise-result",
  "/user-manual/result-list",
  "/user-manual/configure-certificate",
  "/user-manual/student-certificate",
  "/user-manual/staff-certificate",
  "/user-manual/student-id-card",
  "/user-manual/staff-id-card",
  "/user-manual/lesson-planning",
  "/user-manual/home-work",
  "/user-manual/upload-material",
  "/user-manual/summer-home-work",
  "/user-manual/home-work-marking",
  "/user-manual/home-work-marking-list",
  "/user-manual/class-time-table",
  "/user-manual/lecture",
  "/user-manual/courses",
  "/user-manual/course-category",
  "/user-manual/routes",
  "/user-manual/vehicles",
  "/user-manual/assign-vehicles",
  "/user-manual/add-expense",
  "/user-manual/manage-expense",
  "/user-manual/expence-category",
  "/user-manual/asset-type",
  "/user-manual/assets",
  "/user-manual/news",
  "/user-manual/notice",
  "/user-manual/message",
  "/user-manual/chat",
  "/user-manual/question-bank",
  "/user-manual/class-wise-question",
  "/user-manual/sports-type",
  "/user-manual/sports-detail",
  "/user-manual/users",
  "/user-manual/roles",
  "/user-manual/library-books",
  "/user-manual/issue-books",
  "/user-manual/configure-chapter",
  "/user-manual/configure-topic",
  "/user-manual/configure-question",
  "/user-manual/paper-generate",
  "/user-manual/events",
  "/user-manual/visit-website",
  "/user-manual/home",
  "/user-manual/about-us",
  "/user-manual/gallery",
  "/user-manual/classes",
  "/user-manual/sections",
  "/user-manual/nationality",
  "/user-manual/religion",
  "/user-manual/assign-classes",
  "/user-manual/designation",
  "/user-manual/subject",
  "/user-manual/assign-subject",
  "/user-manual/designation",
  "/user-manual/subject",
  "/user-manual/assign-subject",
  "/user-manual/sibling-discount",
  "/user-manual/school-timing",
  "/user-manual/school-manage",
  "/user-manual/configure-scholarship",
  "/user-manual/configure-fee-recipients",
  "/user-manual/configure-fee",
  "/user-manual/configure-salary",
  "/user-manual/student-attendnce",
  "/user-manual/staff-attendnce",
  "/user-manual/students-report",
  "/user-manual/staff-report",
  "/user-manual/staff-accounts",
  "/user-manual/student-accounts",
  "/user-manual/student-recieveables",
  "/user-manual/general-ledger",
  "/user-manual/fee-report",
  "/user-manual/transport-fee-report",
  "/user-manual/inventory-fee-repport",
  "/user-manual/fee-detailed-report",
  "/user-manual/salary-paid",
  "/user-manual/student-feedback",
  "/user-manual/teacher-feedback",
  "/user-manual/postal-report",
  "/user-manual/visitors-report",
  "/user-manual/student-review-report",
  "/user-manual/staff-review-report",
  "/user-manual/leave-report",
  "/user-manual/inventory-report",
  "/user-manual/library-report",
  "/user-manual/expense-report",
  "/user-manual/day-book",
  "/user-manual/profit%20&%20loss",
  "/user-manual/transreport-report",
  "/blog",
  "/contact",
  "/demo",
  "/privacy",
  "/t&c",
  "/help",
  "/faqs",
];

function generateXml(urls) {
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
  <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    ${urls
      .map(
        (url) => `
    <url>
      <loc>${url}</loc>
      <lastmod>${new Date().toISOString()}</lastmod>
      <changefreq>weekly</changefreq>
      <priority>0.8</priority>
    </url>`
      )
      .join("\n")}
  </urlset>`;
  return xml;
}
function generateSitemap() {
  const fullUrls = routes.map((route) => `https://capobrain-sms.vercel.app${route}`);
  const xmlContent = generateXml(fullUrls);

  // Ensure the public directory exists
  const sitemapDir = path.resolve(__dirname, "public");
  if (!fs.existsSync(sitemapDir)) {
    fs.mkdirSync(sitemapDir);
  }

  const sitemapPath = path.resolve(sitemapDir, "sitemap.xml");
  fs.writeFileSync(sitemapPath, xmlContent);

  console.log(`Sitemap generated at ${sitemapPath}`);
}

// Run the function
generateSitemap();
