const fs = require("fs");

// List your React app routes here
const routes = [
  "/",
  "/about",
  "/features/cloud-based-school-managment-system",
  "/features/cutting-edge-technologies",
  "/features/computer-based-exam-solutions",
  "/features/ai-driven-school-management",
  "/features/data-security",
  "/features/students-and-parent-portals",
  "/features/online-daily-diary",
  "/features/school-management-mobile-app",
  "/features/whatsapp-messaging",
  "/features/biometric-attendance",
  "/features/salary-and-fee-management",
  "/features/inventory-management",
  "/features/student-and-staff-ledgers",
  "/features/remainders-for-fee-collection",
  "/features/expense-and-assets-management",
  "/features/online-paper-generation",
  "/features/exams-and-results-management",
  "/features/reporting",
  "/features/multi-campuses-management",
  "/features/school-front-website",
  "/features/transportation-management",
  "/usermanual",
  "/usermanual/dashboard",
  "/usermanual/visitors-meeting",
  "/usermanual/phone-call-log",
  "/usermanual/postal-dispatch",
  "/usermanual/postal-recieve",
  "/usermanual/online-complains-list",
  "/usermanual/configure-front-office",
  "/usermanual/teaching-staff",
  "/usermanual/non-teaching-staff",
  "/usermanual/staff-todos",
  "/usermanual/staff-withdraw",
  "/usermanual/staff-review",
  "/usermanual/feedback-list",
  "/usermanual/new-admission",
  "/usermanual/students-list",
  "/usermanual/online-admissions",
  "/usermanual/family-record",
  "/usermanual/promote-students",
  "/usermanual/withdraw-students",
  "/usermanual/passout-students",
  "/usermanual/students-review",
  "/usermanual/feedback-record",
  "/usermanual/student-attendance",
  "/usermanual/staff-attendance",
  "/usermanual/leave-request",
  "/usermanual/inventory",
  "/usermanual/purchase-inventory",
  "/usermanual/purchase-list",
  "/usermanual/issue-inventory",
  "/usermanual/invoice-list",
  "/usermanual/supplier",
  "/usermanual/recieve-fee",
  "/usermanual/refund-payment",
  "/usermanual/update-fee",
  "/usermanual/update-fee-list",
  "/usermanual/scholarship",
  "/usermanual/fine-management",
  "/usermanual/discounts",
  "/usermanual/student-account-adjust",
  "/usermanual/fee-comitment-list",
  "/usermanual/default-students",
  "/usermanual/calender",
  "/usermanual/salary-cycle",
  "/usermanual/generate-vouchers",
  "/usermanual/print-vouchers",
  "/usermanual/withdraw-amount",
  "/usermanual/students-account",
  "/usermanual/staff-account",
  "/usermanual/supplier-account",
  "/usermanual/family-wise-account",
  "/usermanual/salary-deduction",
  "/usermanual/configure-exam",
  "/usermanual/configure-papers",
  "/usermanual/date-sheet",
  "/usermanual/add-result",
  "/usermanual/subject-wise-result",
  "/usermanual/result-list",
  "/usermanual/configure-certificate",
  "/usermanual/student-certificate",
  "/usermanual/staff-certificate",
  "/usermanual/student-id-card",
  "/usermanual/staff-id-card",
  "/usermanual/lesson-planning",
  "/usermanual/home-work",
  "/usermanual/upload-material",
  "/usermanual/summer-home-work",
  "/usermanual/home-work-marking",
  "/usermanual/home-work-marking-list",
  "/usermanual/class-time-table",
  "/usermanual/lecture",
  "/usermanual/courses",
  "/usermanual/course-category",
  "/usermanual/routes",
  "/usermanual/vehicles",
  "/usermanual/assign-vehicles",
  "/usermanual/add-expense",
  "/usermanual/manage-expense",
  "/usermanual/expence-category",
  "/usermanual/asset-type",
  "/usermanual/assets",
  "/usermanual/news",
  "/usermanual/notice",
  "/usermanual/message",
  "/usermanual/chat",
  "/usermanual/question-bank",
  "/usermanual/class-wise-question",
  "/usermanual/sports-type",
  "/usermanual/sports-detail",
  "/usermanual/users",
  "/usermanual/roles",
  "/usermanual/library-books",
  "/usermanual/issue-books",
  "/usermanual/configure-chapter",
  "/usermanual/configure-topic",
  "/usermanual/configure-question",
  "/usermanual/paper-generate",
  "/usermanual/events",
  "/usermanual/visit-website",
  "/usermanual/home",
  "/usermanual/about-us",
  "/usermanual/gallery",
  "/usermanual/classes",
  "/usermanual/sections",
  "/usermanual/nationality",
  "/usermanual/religion",
  "/usermanual/assign-classes",
  "/usermanual/designation",
  "/usermanual/subject",
  "/usermanual/assign-subject",
  "/usermanual/designation",
  "/usermanual/subject",
  "/usermanual/assign-subject",
  "/usermanual/sibling-discount",
  "/usermanual/school-timing",
  "/usermanual/school-manage",
  "/usermanual/configure-scholarship",
  "/usermanual/configure-fee-recipients",
  "/usermanual/configure-fee",
  "/usermanual/configure-salary",
  "/usermanual/student-attendnce",
  "/usermanual/staff-attendnce",
  "/usermanual/students-report",
  "/usermanual/staff-report",
  "/usermanual/staff-accounts",
  "/usermanual/student-accounts",
  "/usermanual/student-recieveables",
  "/usermanual/general-ledger",
  "/usermanual/fee-report",
  "/usermanual/transport-fee-report",
  "/usermanual/inventory-fee-repport",
  "/usermanual/fee-detailed-report",
  "/usermanual/salary-paid",
  "/usermanual/student-feedback",
  "/usermanual/teacher-feedback",
  "/usermanual/postal-report",
  "/usermanual/visitors-report",
  "/usermanual/student-review-report",
  "/usermanual/staff-review-report",
  "/usermanual/leave-report",
  "/usermanual/inventory-report",
  "/usermanual/library-report",
  "/usermanual/expense-report",
  "/usermanual/day-book",
  "/usermanual/transreport-report",
  "/blog",
  "/contact",
  "/demo",
  "/help",
  "/faq",
];

function generateXml(urls) {
  const xml = `
    <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
      ${urls.map((url) => `<url><loc>${url}</loc></url>`).join("\n")}
    </urlset>
  `;
  return xml;
}

function generateSitemap() {
  const fullUrls = routes.map((route) => `https://capobrain-sms.vercel.app/${route}`);
  const xmlContent = generateXml(fullUrls);

  // Write the XML content to a file
  const sitemapPath = "./public/sitemap.xml"; // Adjust the path as needed
  fs.writeFileSync(sitemapPath, xmlContent);

  console.log(`Sitemap generated at ${sitemapPath}`);
}

// Run the function
generateSitemap();
